import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{
          textAlign: "center",
          backgroundImage: "url(./background.jpg)",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          height: "95vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}>{children}</body>
    </html>
  );
}
